
background = [10, 0, 10]

[canvas]
width = 100
height = 100

[viewport]
width = 1.5
height = 1.5

[camera]
position = [0, 0, -5]
rotation = [0, 0, 0]


[[spheres]]
position = [0, -1, 3]
radius = 1
color = [255, 0, 0]
specular = 60
reflective = 0.3

[[spheres]]
position = [2, 0, 4]
radius = 1
color = [0, 0, 255]
specular = 50
reflective = 0.4

[[spheres]]
position = [-2, 0, 4]
radius = 1
color = [0, 255, 0]
specular = 100
reflective = 0.7

[[spheres]]
position = [0, -5001, 0]
radius = 5000
color = [255, 255, 0]
specular = 1000
reflective = 0.5

[[lights]]
type = "ambient"
intensity = 0.2

[[lights]]
type = "point"
intensity = 0.4
position = [2, 1, 0]

[[lights]]
type = "directional"
intensity = 0.4
direction = [-1, -4, 4]